---
title: "Organize Data Notebook"
---

```{r}
#| label: setup
#| include: false
library(here)
source(here("utils","check_packages.R"))
source(here("utils","functions.R"))


```


```{r}

library(readr)
library(dplyr)

ipums_data <- read_fwf(
  file = "data/data_raw/gendergrad.dat.gz",
  col_positions = fwf_cols(
    year     = c(1, 4),
    serial   = c(5, 12),
    pernum   = c(13, 16),
    perwt    = c(17, 26),
    sex      = c(27, 27),
    educ     = c(28, 29),
    educd    = c(30, 32),
    empstat  = c(33, 33),
    empstatd = c(34, 35)
  ),
  col_types = cols(.default = "i", perwt = "d")
)

#Clean and organize the data

cleaned_dataset <- ipums_data |>
  mutate(
    sex = factor(sex, levels = c(1, 2), labels = c("Male", "Female")),
    empstat = factor(empstat, levels = c(1, 2, 3),
                     labels = c("Employed", "Unemployed", "NIU")),
    
    # Recode educd into meaningful categories
    educd_cat = case_when(
  educd %in% c(2:61) ~ "No Degree",
  educd %in% c(62, 63) ~ "High School",
  educd %in% c(64, 65, 81, 91) ~ "Some College",
  educd == 101 ~ "Bachelor's",
  educd %in% c(114, 115, 116) ~ "Graduate Degree",
  TRUE ~ NA_character_
),
educd_cat = factor(educd_cat, levels = c(
  "No Degree", "High School", "Some College", "Bachelor's", "Graduate Degree"
))
  ) |>
  select(year, perwt, sex, educd_cat, empstat)

# Saved cleaned dataset as RData
save(cleaned_dataset, file = here("data", "data_constructed", "analytical_data.RData"))

```

This quarto doc is used to organize the data.